# -*- coding: utf-8 -*-
"""Convolutional Transform Transformer Smoke Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooG3j1Gm_IvgNB6x1_fIYNTlE95rwS9J
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AngshulMajumdar/Convolutional-transformed-Transformer-API.git
# %cd Convolutional-transformed-Transformer-API
!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AngshulMajumdar/Convolutional-transformed-Transformer-API.git
# %cd Convolutional-transformed-Transformer-API
!pip install -e .

!pytest tests/test_smoke.py -q
!pytest tests/test_decoder_only_api.py -q
!pytest tests/test_encoder_decoder_api.py -q
!pytest tests/test_seq2seq.py -q